# Generated by Django 4.1.5 on 2023-02-24 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.model_support.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Customer Name', max_length=256)),
                ('description', models.CharField(default='Default Customer Description', max_length=1024)),
                ('address', models.CharField(default='Default Customer Address', max_length=512)),
                ('email', models.EmailField(default='default.customer@email.com', max_length=64)),
                ('phone_number', models.CharField(default='+1234567890', max_length=16)),
            ],
            bases=(main.model_support.mixins.NotesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='documents/%Y/%m/%d')),
                ('date_uploaded', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Employee Name', max_length=64)),
                ('description', models.CharField(default='Default Employee Description', max_length=128)),
                ('phone_number', models.CharField(default='+1234567890', max_length=16)),
                ('email', models.EmailField(default='default.customer@email.com', max_length=64)),
                ('payment_status', models.CharField(default='Payment Status Not Set', max_length=128)),
            ],
            bases=(main.model_support.mixins.NotesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Group Name', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(default='+1234567890', max_length=64)),
            ],
            bases=(main.model_support.mixins.NotesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Profit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_earned', models.DateField(auto_now_add=True)),
                ('amount', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Team Name', max_length=128)),
                ('description', models.CharField(default='Default Team Description', max_length=256)),
                ('employees', models.ManyToManyField(to='main.employee')),
                ('managers', models.ManyToManyField(to='main.manager')),
                ('team_leader', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='foreman', to='main.employee')),
            ],
            bases=(main.model_support.mixins.NotesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Default Task Title', max_length=1024)),
                ('description', models.CharField(default='Default Task Description', max_length=2048)),
                ('date_open', models.DateField(auto_now_add=True)),
                ('deadline', models.DateField(null=True)),
                ('date_done', models.DateField(null=True)),
                ('is_done', models.BooleanField(default=False)),
                ('managers', models.ManyToManyField(to='main.manager')),
            ],
            bases=(main.model_support.mixins.NotesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_added', models.DateTimeField(auto_now_add=True)),
                ('content', models.CharField(default='Default Note Content', max_length=1024)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='manager',
            name='profit',
            field=models.ManyToManyField(to='main.profit'),
        ),
        migrations.AddField(
            model_name='manager',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Default Deal Title', max_length=1024)),
                ('description', models.CharField(default='Default Deal Description', max_length=2048)),
                ('date_open', models.DateField(auto_now_add=True)),
                ('deadline', models.DateField(null=True)),
                ('date_done', models.DateField(null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('budget', models.FloatField(default=0.0, null=True)),
                ('expenses', models.FloatField(default=0.0, null=True)),
                ('customers', models.ManyToManyField(to='main.customer')),
                ('deal_groups', models.ManyToManyField(to='main.group')),
                ('documents', models.ManyToManyField(to='main.document')),
                ('supervisors', models.ManyToManyField(to='main.manager')),
                ('tasks', models.ManyToManyField(to='main.task')),
            ],
            bases=(main.model_support.mixins.NotesMixin, models.Model),
        ),
        migrations.AddField(
            model_name='customer',
            name='employees',
            field=models.ManyToManyField(to='main.employee'),
        ),
        migrations.AddField(
            model_name='customer',
            name='profit',
            field=models.ManyToManyField(to='main.profit'),
        ),
    ]
