# Generated by Django 4.1.5 on 2023-02-24 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customers', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.customer')),
                ('deals', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.deal')),
                ('employees', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.employee')),
                ('groups', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.group')),
                ('managers', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.manager')),
                ('tasks', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.task')),
                ('teams', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.team')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
