# Generated by Django 4.1.5 on 2023-03-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_association_delete_chief'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='teams',
            field=models.ManyToManyField(to='main.team'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='default.employee@email.com', max_length=64),
        ),
    ]
