# Generated by Django 4.1.5 on 2023-03-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_association_customers_alter_association_deals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
