# Generated by Django 4.1.5 on 2023-03-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_note_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='customers',
            field=models.ManyToManyField(to='main.customer'),
        ),
        migrations.AlterField(
            model_name='association',
            name='deals',
            field=models.ManyToManyField(to='main.deal'),
        ),
        migrations.AlterField(
            model_name='association',
            name='employees',
            field=models.ManyToManyField(to='main.employee'),
        ),
        migrations.AlterField(
            model_name='association',
            name='groups',
            field=models.ManyToManyField(to='main.group'),
        ),
        migrations.AlterField(
            model_name='association',
            name='managers',
            field=models.ManyToManyField(to='main.manager'),
        ),
        migrations.AlterField(
            model_name='association',
            name='tasks',
            field=models.ManyToManyField(to='main.task'),
        ),
        migrations.AlterField(
            model_name='association',
            name='teams',
            field=models.ManyToManyField(to='main.team'),
        ),
    ]
