# Generated by Django 4.1.5 on 2023-03-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_association_customers_alter_association_deals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='title',
            field=models.CharField(default='Default Association Name', max_length=1024),
        ),
    ]
