# Generated by Django 4.1.5 on 2023-03-10 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_association_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='description',
            field=models.CharField(default='Default Association Description', max_length=1024),
        ),
    ]
