# Generated by Django 4.1.5 on 2023-03-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_association_chief'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='notes',
            field=models.ManyToManyField(to='main.note'),
        ),
        migrations.AddField(
            model_name='deal',
            name='notes',
            field=models.ManyToManyField(to='main.note'),
        ),
        migrations.AddField(
            model_name='employee',
            name='notes',
            field=models.ManyToManyField(to='main.note'),
        ),
        migrations.AddField(
            model_name='manager',
            name='notes',
            field=models.ManyToManyField(to='main.note'),
        ),
        migrations.AddField(
            model_name='task',
            name='notes',
            field=models.ManyToManyField(to='main.note'),
        ),
        migrations.AddField(
            model_name='team',
            name='notes',
            field=models.ManyToManyField(to='main.note'),
        ),
    ]
